version: '2'
services:
  courses-db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: courses
      MYSQL_HOST: courses-db
  courses-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4001 -b '0.0.0.0'"
    ports:
      - "4001:40001"
    depends_on:
      - courses-db
